language: elixir
services:
  - redis-server
before_install:
  - cp config/dev_demo.exs config/dev.exs
  - ls config/
elixir:
  - 1.3.4
  - 1.4
script:
  - mix credo --strict
  # - mix dialyzer
  - mix test
otp_release:
  - 19.2
  - 20.0

matrix:
  allow_failures:
    - otp_release: 20.0
