language: elixir
before_install:
  - cp config/dev_demo.exs config/dev.exs
  - ls config/
elixir:
  - 1.3.4
  - 1.4
script:
  - mix credo --strict
  # - mix dialyzer
  - mix test
otp_release:
  - 19.2